export const CLAIMS_CONFIG = {
	DAILY_COOLDOWN_HOURS: 24,
	QUICK_COOLDOWN_HOURS: 4,
	QUICK_REWARD_MULTIPLIER: 0.4,
	BASE_FOOD_ITEMS: 3,
	BASE_DRINK_ITEMS: 3,
	BASE_HYGIENE_ITEMS: 2,
	BASE_CARE_ITEMS: 2,
	BASE_EGG_CHANCE: 0.35,
} as const;

export const EXPEDITION_CONFIG = {
	BASE_FOOD_ITEMS: 2,
	BASE_DRINK_ITEMS: 2,
	BASE_HYGIENE_ITEMS: 1,
	BASE_CARE_ITEMS: 1,
	MIN_EGG_CHANCE: 0.05,
	MAX_EGG_CHANCE: 0.18,
} as const;
